### ISSUE TITLE
Update repo to make license explicit

### ISSUE THREAD

**Issue by jantic** [nci/FourCastNeXt#7]
Hello!  Love this project and I can't believe this repo flew under my radar until this point. It's a great advance in making this stuff practical. I'm interested in using this project but the [license isn't explicitly set on the repo](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository ).  Would you be able to update that?  Thanks!

**Comment by edisonguo** [comment]
Thank you for your kind words! We intended to use Apache 2.0 licence for this project but somehow omitted the licence file in the repo. Now I updated the repo to include the licence file.

**Comment by jantic** [comment]
Thank you!
